image = "<path to a PyTorch NGC (with mpi4py) based image>"

mounts = ["<the current working directory containing the .py script>:/scratch"]

workdir = "/scratch"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"


