image = "/capstor/store/cscs/cscs/jupyter/pytorch/pytorch-summer-university-25.05-py3.sqsh"

mounts = ["<the current working directory containing the .py script>:/scratch"]

workdir = "/scratch"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"


